platform :ios, '8.0'

source 'https://github.com/CocoaPods/Specs.git'

def target_name
	'PrivatePodA'
end

def import_pods	
	pod 'CocoaLumberjack'
end

target target_name do
	use_frameworks!
	import_pods
end